### ISSUE TITLE
Update fullcalendar styles to material

### ISSUE THREAD

**Issue by tnguyen14** [cbta/cbtallc.com#40]
https://github.com/jackyliang/Material-Design-For-Full-Calendar

**Comment by jvermilyea** [comment]
Is this for me to look at and see about these and styling?

I am interviewing two new potential people, one tomorrow and one Thursday.

I am thinking that being the online calendar would not be optional for them. It’s a good way for patients to fill schedulees.





James A. Vermilyea, Ph.D., ABPP, Director
Cognitive Behavior Therapy Associates, LLC
394 Lowell Street, Suite 15
Lexington, MA 02420

Main CBTA telephone line: 617-531-7133
Fax:	781-281-0644
Dr. Vermilyea's Direct line: 339-224-7695

For returning patients only, please go to www.cbtallc.com/calendar <http://www.cbtallc.com/calendar> to see Dr. Jim's availability. Appointment requests are only valid once confirmed by Dr. Jim.

Please note: This communication is private, confidential and protected by state and federal law. If you get this communication in error, please notify the sender and destroy the message whether they are electronic or paper copies. When you supply personal information over the Internet or via email that the privacy of the information supplied cannot be guaranteed by CBTA, LLC. By using these methods you are acknowledging that you accept responsibility for any risk to your personal health care information or personal identifiers. If you have concerns about this we encourage you to contact us via more conventional means such as telephone, fax or United States post.

**Comment by tnguyen14** [comment]
No Jim, this would be for me to work on. 

I like putting them on the online calendar though :)

**Comment by jvermilyea** [comment]
That's fine I thought I'd ask that's all
