### ISSUE TITLE
add dr. stoddard

### ISSUE THREAD

**Issue by tnguyen14** [cbta/cbtallc.com#44]
>Eve P. Stoddard, PhD

>Dr. Stoddard is a licensed clinical psychologist.  As a clinician, Dr. Stoddard believes in establishing a collaborative therapeutic relationship to help clients reach their fullest potential.  She regularly works with adults with issues such as: depression; Generalized Anxiety Disorder; social phobia; Obsessive-Compulsive Disorder; trauma and Posttraumatic Stress Disorder; high functioning Autism Spectrum Disorders (Asperger’s Disorder); ADHD; adjustment disorders; career issues; self-esteem; work-related anxiety and stress; and relationship difficulties.

>Dr. Stoddard received her undergraduate degree in Film Production with a minor in psychology from Scripps College in Claremont, California.  She received a Master’s Degree and PhD in Clinical Psychology, with a subspecialization in neuropsychology, from Drexel University in Philadelphia, PA.  Her postdoctoral fellowship was in Pediatric Neuropsychology at Mt. Washington Pediatric Hospital, an affiliate of Johns Hopkins Hospital, in Baltimore, MD. 

>She has worked in various settings, including a college counseling center, hospitals, private practices, and a military mental health clinic.  She utilizes supportive therapy, Cognitive Behavioral Therapy (CBT), Cognitive Processing Therapy (CPT), Prolonged Exposure Therapy (PE) and Acceptance and Commitment Therapy (ACT).  Thus, she employs a specific therapy or combination of therapies that are most effective in treating the individual.

**Comment by jvermilyea** [comment]
Did you mean for me to check this text for just that you had put it up?

Thank you,

Jim

James A. Vermilyea, Ph.D., ABPP, Director
Cognitive Behavior Therapy Associates, LLC
394 Lowell Street, Suite 15
Lexington, MA 02420

Main CBTA telephone line: 617-531-7133
Fax:	781-281-0644
Dr. Vermilyea's Direct line: 339-224-7695

For returning patients only, please go to www.cbtallc.com/calendar <http://www.cbtallc.com/calendar> to see Dr. Jim's availability. Appointment requests are only valid once confirmed by Dr. Jim.

Please note: This communication is private, confidential and protected by state and federal law. If you get this communication in error, please notify the sender and destroy the message whether they are electronic or paper copies. When you supply personal information over the Internet or via email that the privacy of the information supplied cannot be guaranteed by CBTA, LLC. By using these methods you are acknowledging that you accept responsibility for any risk to your personal health care information or personal identifiers. If you have concerns about this we encourage you to contact us via more conventional means such as telephone, fax or United States post.

**Comment by tnguyen14** [comment]
Neither. Maybe you subscribed to all issues, so you get emailed for issue notification. I just put it up here so it's on my todo list.

**Comment by jvermilyea** [comment]
oh ok

James A. Vermilyea, Ph.D., ABPP, Director
Cognitive Behavior Therapy Associates, LLC
394 Lowell Street, Suite 15
Lexington, MA 02420

Main CBTA telephone line: 617-531-7133
Fax:	781-281-0644
Dr. Vermilyea's Direct line: 339-224-7695

For returning patients only, please go to www.cbtallc.com/calendar <http://www.cbtallc.com/calendar> to see Dr. Jim's availability. Appointment requests are only valid once confirmed by Dr. Jim.

Please note: This communication is private, confidential and protected by state and federal law. If you get this communication in error, please notify the sender and destroy the message whether they are electronic or paper copies. When you supply personal information over the Internet or via email that the privacy of the information supplied cannot be guaranteed by CBTA, LLC. By using these methods you are acknowledging that you accept responsibility for any risk to your personal health care information or personal identifiers. If you have concerns about this we encourage you to contact us via more conventional means such as telephone, fax or United States post.
