### ISSUE TITLE
On the top of the page can we add....

### ISSUE THREAD

**Issue by jvermilyea** [cbta/cbtallc.com#45]
If I click on appointments, it's not immediately obvious how  to get back the to the main page where the therapists are.

Could we add a "Main Page" or "Therapists" button (the CBTA logo does this but it's not obvious). YOu know best if it's standard that sites work this way leave it... ;)

Thank you

**Comment by tnguyen14** [comment]
Heh, sorry this is a year late response.

Yeah, I think most sites just have the logo to go home, or use the built-in back button on the browser.
