### ISSUE TITLE
Update Jim's profile image

### ISSUE THREAD

**Issue by tnguyen14** [cbta/cbtallc.com#47]
![jim](https://cloud.githubusercontent.com/assets/1652595/24929118/df908166-1ed2-11e7-82d5-bea99f85c268.jpg)

**Comment by jvermilyea** [comment]
How long does it take for these the update because I don't see it on the
home page

**Comment by tnguyen14** [comment]
I haven't done it yet. I just created the issue. Once done, this issue will
be closed.

**Comment by jvermilyea** [comment]
Oops sorry.

**Comment by tnguyen14** [comment]
@jvermilyea do you have a full res version of this?
